language: objective-c
osx_image: xcode12.5
jobs:
  include:
    - stage: Unit tests
      name: iOS
      script:
      - xcodebuild -workspace OktaAuthSdk.xcworkspace -scheme "OktaAuthNative iOS" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - stage: Dependency Manager Validation
      name: SPM
      script:
      - swift test
    - stage: Dependency Manager Validation
      name: CocoaPods
      script:
      - pod lib lint --allow-warnings
    # Disable carthage as it requires --use-xcframeworks. It's time-consuming operation.
    # - stage: Dependency Manager Validation
    #   name: Carthage
    #   script:
    #   - carthage build --no-skip-current
