name: Okta Auth iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  UnitTests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: iOS
      run: xcodebuild -workspace OktaAuthSdk.xcworkspace -scheme "OktaAuthNative iOS" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - name: Swift
      run: swift test -v
  PackageValidation:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Cocoapods
      run: pod lib lint --allow-warnings
